apiVersion: apps/v1
kind: Deployment
metadata:
  name: feedpage-deployment
  namespace: feedpage
  labels:
    app: feedpage
spec:
  revisionHistoryLimit: 1
  replicas: 1 # pods running the service
  selector:
    matchLabels:
      app: feedpage
  template:
    metadata:
      labels:
        app: feedpage
      annotations:
        sidecar.istio.io/proxyCPU: "50m"
        sidecar.istio.io/proxyMemory: "64Mi"
        sidecar.istio.io/proxyCPULimit: "200m"
        sidecar.istio.io/proxyMemoryLimit: "128Mi"  
    spec:
      imagePullSecrets:
        - name: ncr-regcred
      containers:
        - name: feedpage-service
          image: 970547342771.dkr.ecr.ap-northeast-2.amazonaws.com/iteamoa/feedpage:ef71fe1
          ports:
            - containerPort: 80 # Check container's exposed port 
