apiVersion: v1
kind: Service
metadata:
  name: feedpage-service
  namespace: feedpage-namespace
spec:
  selector:
    svc: feedpage
  ports:
    - protocol: TCP
      port: 80             # Public-facing port/Service port
      targetPort: 8080       # Container port
  type: ClusterIP            # Exposes the service