apiVersion: apps/v1
kind: Deployment
metadata:
  name: feedpage-service-deployment
  namespace: feed-namespace  # Match the Fargate namespace
  labels:
    app: fargate
spec:
  replicas: 1  # Two pods running the service
  selector:
    matchLabels:
      app: fargate
  template:
    metadata:
      labels:
        app: fargate
    spec:
      containers:
      - name: feedpage-service
        image: 970547342771.dkr.ecr.ap-northeast-2.amazonaws.com/iteamoa/feedpage:latest
        ports:
        - containerPort: 8000  # Check container's exposed port 