apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: feed-ingress
  namespace: feed-namespace
  annotations:
    kubernetes.io/ingress.class: "alb"
    alb.ingress.kubernetes.io/certificate-arn: 
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    alb.ingress.kubernetes.io/group.name: "backend-api"  
    alb.ingress.kubernetes.io/healthcheck-path: "/"
spec:
  ingressClassName: alb
  rules:
  - host: iteamoa-api.brynnpark.cloud
    http:
      paths:
      - path: /feed
        pathType: Prefix
        backend:
          service:
            name: feed-service
            port:
              number: 80
      